[project]
name = "market-api"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.128.0",
    "pytm-shared",
]

[tool.uv.sources]
pytm-shared = { path = "../shared" }
