[project]
name = "pytm-shared"
version = "0.1.0"
description = "Shared utilities for Paytm Money projects"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "redis>=6.4.0",
    "pydantic>=2.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"